#!/bin/bash

ifconfig | grep -q tun0; VPNTUN=$?
case $VPNTUN in
  0)
    VPN=🛡
    VPNCOLOR="green"
    ;;
  1 | *)
    VPN=🚨
    VPNCOLOR="red"
    ;;
esac

ping -c 2 8.8.8.8 &> /dev/null; WANPING=$?
case $WANPING in
  0)
    WAN=📡
    WANCOLOR="green"
    WANIP=$(curl ipv4.icanhazip.com | cut -d "." -f 3-4)
    ;;
  1 | *)
    WAN=📡
    WANCOLOR="red"
    WANIP=🚧
    ;;
esac

ping -c 2 192.168.10.42 &> /dev/null; LANPING=$?
case $LANPING in
  0)
    LAN=🏡
    LANCOLOR="green"
    LANIP=$(ifconfig | grep -A 1 wlp3s0 | grep inet | cut -d " " -f 10 | cut -d "." -f 3-4)
    ;;
  1 | *)
    LAN=🏡
    LANCOLOR="red"
    LANIP=🚧
    ;;
esac

LOC=$(curl ipinfo.io/city?token=28c0d7bbfaba3d)

echo "  🛰 <b>| [<span background=\"$VPNCOLOR\">$VPN</span>]($LOC) [<span background=\"$WANCOLOR\">$WAN</span>]($WANIP) [<span background=\"$LANCOLOR\">$LAN</span>]($LANIP) |</b>"
