#!/bin/bash

DRIVEROOT=$( df -h 2>/dev/null | grep root | cut -d "G" -f 3 | sed -e "s/^\( *\)//;s/$/G/" )
DRIVEM2=$( df -h 2>/dev/null | grep sdb1 | cut -d "G" -f 3 | sed -e "s/^\( *\)//;s/$/G/" )

echo "  💽<b>| 💾M2:$DRIVEM2 💾/:$DRIVEROOT |</b>" 
